<?php

namespace FrontBundle\Repository;

/**
 * RealisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealisationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastThreeRealisation()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select('R')
            ->from('FrontBundle:Realisation', 'R')
            ->setMaxResults( 4 );
        $query = $qb->getQuery();
        $result = $query->getResult();
        return $result;
    }
}
